include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    file_names : ignore
    avoid_unnecessary_containers: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    depend_on_referenced_packages: ignore
    prefer_const_literals_to_create_immutables: ignore
    library_private_types_in_public_api: ignore
    avoid_print: ignore
    sized_box_for_whitespace: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_typing_uninitialized_variables: ignore
    constant_identifier_names: ignore
    unused_element: ignore
    prefer_const_declarations: ignore
    must_be_immutable: ignore
    unused_field: ignore